ECommerce/EBazaar/urls.py
from django.urls import path
from . import views

app_name = "EBazaar"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:category_id>", views.index, name="index"),
    path("category/<int:category_id>/products", views.category, name="category"),
    path("category/<int:category_id>/product/<int:product_id>", views.product_details, name="product_details"),
    path("category/<int:category_id>", views.category, name="category"),
    path("categories", views.display_categories, name="all_categories"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("your-cart", views.view_cart, name="view_cart"),
    path("add-to-cart/<int:product_id>", views.add_to_cart, name="add_to_cart"),
]

ECommerce/ECommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('EBazaar.urls')),
]

ECommerce/EBazaar/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

USER_TYPE = [
    ('user1', 'Wholesaler'),
    ('user2', 'Seller'),
    ('user3', 'Customer'),
]

class User(AbstractUser):
    user_type = models.CharField(max_length=50, choices=USER_TYPE, default='user3')

class Category(models.Model):
    category_name = models.CharField(max_length=50, blank=False)
    category_image = models.CharField(max_length=200, blank=False)

    def __str__(self):
        return f"ID:{self.pk}, Name: {self.category_name}"

class Collection(models.Model):
    category_id = models.ForeignKey(Category, on_delete=models.DO_NOTHING, name="collection_category")
    collection_name = models.CharField(max_length=50, blank=False)
    season = models.CharField(max_length=50, blank=False)
    image = models.CharField(max_length=200, blank=False)

    def __str__(self):
        return f"Name: {self.collection_name}"

class Product(models.Model):
    SKU = models.CharField(max_length=3)
    product_name = models.CharField(max_length=50, blank=False)
    description = models.CharField(max_length=200, blank=False)
    sizes = models.CharField(max_length=50, default=None, blank=True)
    colors = models.CharField(max_length=50, default=None, blank=True)
    image = models.CharField(max_length=200)
    price = models.FloatField()
    weight = models.FloatField()
    quantity = models.IntegerField()
    seller_id = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="product_seller")
    category_id = models.ForeignKey(Category, on_delete=models.DO_NOTHING, related_name="product_category")
    
    def __str__(self):
        return f"ID: {self.pk}, Name: {self.product_name}, Category ID: {self.category_id} Price: {self.price}"
    
class Cart(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="cart_user")
    created_at = models.DateTimeField(auto_now=True)
    total_amount = models.FloatField()
# auto_now=True //For object updation time
# auto_now_add=True //For object creation time
    def __str__(self):
        return f"ID: {self.pk}, TimeStamp: {self.created_at}"

class CartItem(models.Model):
    cart_id = models.ForeignKey(Cart, on_delete=models.DO_NOTHING, related_name="cart_item_id")
    product_id = models.ForeignKey(Product, on_delete=models.DO_NOTHING, related_name="cart_product")
    quantity = models.IntegerField()
    total_price = models.FloatField()

STATUS_CHOICES = [
    ('status1', 'Processing'),
    ('status2', 'Shipped'),
    ('status3', 'Delivered'),
]

class Order(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="order_user")
    order_date = models.DateTimeField(auto_now_add=False)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='Processing')
    total_amount = models.FloatField()

    def __str__(self):
        return f"ID: {self.pk}, Delivery Date: {self.order_date}"
    
class OrderItem(models.Model):
    order_id = models.ManyToManyField(Order)
    product_id = models.ForeignKey(Product, on_delete=models.DO_NOTHING, related_name="order_product")
    quantity = models.IntegerField()
    unit_price = models.FloatField()

    def __str__(self):
        return f"ID: {self.pk}, Product ID: {self.product_id}, Quantity: {self.quantity}, Unit Price: {self.unit_price}, Total Price: {self.quantity * self.unit_price}"

class Review(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.DO_NOTHING, related_name="review_product")
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="review_user")
    rating = models.IntegerField()
    review_text = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"ID: {self.pk}, User ID: {self.user_id}, Ratings: {self.rating}"

class Wishlist(models.Model):
    user_id = models.ForeignKey(User,on_delete=models.DO_NOTHING, related_name="wishlist_user")
    products = models.ManyToManyField(Product)

class Wholesaler(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="wholesaler")
    company_name = models.CharField(max_length=50)

    def __str__(self):
        return f"ID: {self.pk}, User ID: {self.user_id}, Company Name: {self.company_name}"
    
class Auction(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.DO_NOTHING, related_name="auction_product_id")
    wholesaler_id = models.ForeignKey(Wholesaler, on_delete=models.DO_NOTHING, related_name="auctioner")
    start_time = models.DateTimeField(auto_now=True)
    end_time = models.DateTimeField(auto_now=True)
    starting_bid = models.FloatField()
    current_highest_bid = models.FloatField()
    status = models.BooleanField(default=True)

    def __str__(self):
        return f"ID: {self.pk},Product ID: {self.product_id}, Auctioner: {self.wholesaler_id}, Status: {self.status}"

class Bid(models.Model):
    auction_id = models.ForeignKey(Auction, on_delete=models.DO_NOTHING, related_name="bid_auction") 
    wholsaler_id = models.ForeignKey(Wholesaler, on_delete=models.DO_NOTHING, related_name="bid_user")
    bid_amount = models.FloatField()
    bid_time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"ID: {self.pk}, User ID:{self.user_id}, Bidding Price: {self.bid_amount}"

ECommerce/EBazaar/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import User,Category, Product, Cart, CartItem, Order, OrderItem, Review, Wishlist, Wholesaler, Auction, Bid, Collection
from django.contrib.auth.models import Group

# Create your views here.
def login_view(request):
    # if request.user.is_authenticated:
    #     return HttpResponseRedirect(reverse("EBazaar:index"))
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("EBazaar:index"))
        else:
            return render(request, "EBazaar/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "EBazaar/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("EBazaar:index"))

# def register(request):
#     if request.user.is_authenticated:
#         return HttpResponseRedirect(reverse("EBazaar:index"))
#     if request.method == "POST":
#         username = request.POST["username"]
#         email = request.POST["email"]
#         user_type = request.POST["user_type"]

#         # Ensure password matches confirmation
#         password = request.POST["password"]
#         confirmation = request.POST["confirmation"]
#         if password != confirmation:
#             return render(request, "EBazaar/register.html", {
#                 "message": "Passwords must match."
#             })

#         # Attempt to create new user
#         try:
#             user = User.objects.create_user(username, email, password, user_type=user_type)
#             user.save()
#         except IntegrityError:
#             return render(request, "EBazaar/register.html", {
#                 "message": "Username already taken."
#             })
#         login(request, user)
#         return HttpResponseRedirect(reverse("EBazaar:index"))
#     else:
#         return render(request, "EBazaar/register.html")

def register(request):
    # if request.user.is_authenticated:
    #     return HttpResponseRedirect(reverse("EBazaar:index"))
    
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        user_type = request.POST["user_type"]
        company = request.POST["company_name"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]

        # Ensure password matches confirmation
        if password != confirmation:
            return render(request, "EBazaar/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create a new user
        try:
            user = User.objects.create_user(username, email, password, user_type=user_type)
            
            # Add the user to a group based on user_type
            if user_type == "Wholesaler":
                wholesaler_group = Group.objects.get(name="WholesalerGroup")
                user.groups.add(wholesaler_group)
                user.is_staff = True
                user.save()
                wholesaler = Wholesaler.objects.create(user_id=user,company_name=company)
                wholesaler.save()
            elif user_type == "Seller":
                seller_group = Group.objects.get(name="SellerGroup")
                user.groups.add(seller_group)
                user.is_staff = True
                user.save()

        except IntegrityError:
            return render(request, "EBazaar/register.html", {
                "message": "Username already taken."
            })

        # Log in the user
        login(request, user)
        cart = Cart.objects.create(user_id=user,total_amount=0.0)
        cart.save()

        # Redirect the Wholesaler to the admin page
        if user_type == "Wholesaler" or user_type == "Seller":
            return HttpResponseRedirect(reverse("admin:index"))
        else:
            return HttpResponseRedirect(reverse("EBazaar:index"))

    else:
        return render(request, "EBazaar/register.html")

def index(request, category_id=None):
    # Display all Products
    try:
        if category_id is None:
            products = Product.objects.all()
        else:
            products = Product.objects.filter(category_id=category_id)
        total_products = products.count()
        chunked_products = [products[i:i+4] for i in range(0, total_products, 4)]

    except IntegrityError:
        products = "No Products Yet."

    # Display Slider
    sliders = Collection.objects.all()

    cart = Cart.objects.get(user_id=request.user.pk)
    cart_items = CartItem.objects.filter(cart_id=cart.pk)
    cart_products = [Product.objects.get(pk=item.product_id.pk) for item in cart_items]
    categories = [Category.objects.filter(pk=product.pk) for product in Product.objects.all()]
    zipped_data = zip(cart_products,cart_items)
    return render(request, "EBazaar/index.html",{
        "all_products":chunked_products,
        "all_categories":categories,
        "sliders":sliders,
        "cart":cart,
        "cart_products":cart_products,
        "cart_items":cart_items,
        "zipped_data":zipped_data
    })

def category(request, category_id):
    try:
        products = Product.objects.filter(category_id=category_id)
    except IntegrityError:
        products = "No Products Yet."
    total_products = products.count()
    chunked_products = [products[i:i+4] for i in range(0, total_products, 4)]

    cart = Cart.objects.get(user_id=request.user.pk)
    cart_items = CartItem.objects.filter(cart_id=cart.pk)
    cart_products = [Product.objects.get(pk=item.product_id.pk) for item in cart_items]
    categories = [Category.objects.filter(pk=product.pk) for product in Product.objects.all()]
    zipped_data = zip(cart_products,cart_items)
    return render(request, "EBazaar/product.html",{
        "all_products":chunked_products,
        "all_categories":categories,
        "cart":cart,
        "cart_products":cart_products,
        "cart_items":cart_items,
        "zipped_data":zipped_data
    })

def display_categories(request):
    cart = Cart.objects.get(user_id=request.user.pk)
    cart_items = CartItem.objects.filter(cart_id=cart.pk)
    cart_products = [Product.objects.get(pk=item.product_id.pk) for item in cart_items]
    categories = [Category.objects.filter(pk=product.pk) for product in Product.objects.all()]
    zipped_data = zip(cart_products,cart_items)
    return render(request, "EBazaar/all_categories.html",{
        "all_categories":categories,
        "cart":cart,
        "cart_products":cart_products,
        "cart_items":cart_items,
        "zipped_data":zipped_data
    })

def product_details(request,category_id,product_id):
    try:
        product = Product.objects.get(pk=product_id)
        category = Category.objects.get(pk=category_id)
        category_products = Product.objects.filter(category_id=category_id)
        total_products = category_products.count()
        chunked_products = [category_products[i:i+4] for i in range(0, total_products, 4)]

        cart = Cart.objects.get(user_id=request.user.pk)
        cart_items = CartItem.objects.filter(cart_id=cart.pk)
        cart_products = [Product.objects.get(pk=item.product_id.pk) for item in cart_items]
        categories = [Category.objects.filter(pk=product.pk) for product in Product.objects.all()]
        zipped_data = zip(cart_products,cart_items)
    except IntegrityError:
        product = "No Product Found"
        categories = "No Category Found"
    return render(request, "EBazaar/product-detail.html",{
        "product":product,
        "category":category,
        "all_products":chunked_products,
        "all_categories":categories,
        "cart_products":cart_products,
        "cart":cart,
        "cart_items":cart_items,
        "zipped_data":zipped_data
    })

def view_cart(request):
    # if request.method == 'POST':
    #     quantity = request.POST["num-product1"]
    #     update_cart = Cart.objects.get(user_id=request.user.pk)
    #     cart_items = CartItem.objects.get(cart_id=cart_)
    try:
        cart = Cart.objects.get(user_id=request.user.pk)
        cart_items = CartItem.objects.filter(cart_id=cart.pk)
        cart_products = [Product.objects.get(pk=item.product_id.pk) for item in cart_items]
        categories = [Category.objects.filter(pk=product.pk) for product in Product.objects.all()]
        zipped_data = zip(cart_products,cart_items)
    except IntegrityError:
        cart_items = "No Cart Items"
    for product, item in zipped_data:
        print(product.price)
        print(f"Hello {item.total_price}")
    return render(request, "EBazaar/shopping-cart.html",{
        "cart_products":cart_products,
        "all_categories":categories,
        "cart":cart,
        "cart_items":cart_items,
        "zipped_data":zipped_data
    })

def add_to_cart(request, product_id):
    total_quantity = 2
    product = Product.objects.get(pk=product_id)
    if request.method == "POST":
        total_quantity = request.POST["quantity"]
    try:
        new_cart = Cart.objects.get(user_id=request.user)
    except Cart.DoesNotExist:
        new_cart = Cart.objects.create(user_id=request.user,total_amount=0.0)
    
    new_cart_item = CartItem.objects.create(cart_id=new_cart,product_id=product,quantity=total_quantity,total_price=(int(total_quantity)*product.price))
    new_cart.total_amount += (int(total_quantity)*product.price)
    new_cart.save()

ECommerce/EBazaar/templates/EBazaar/login.html
{% extends "EBazaar/layout2.html" %}

{% block body %}

<div style="position: relative; margin: 100px;">
    <h2>Login</h2>

    {% if message %}
    <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'EBazaar:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'EBazaar:register' %}">Register here.</a>
</div>

{% endblock %}

ECommerce/EBazaar/templates/EBazaar/product-detail.html
{% extends "EBazaar/layout2.html" %}
{% load static %}
{% block body %}

<!-- breadcrumb -->
<div class="container" style="margin-top: 50px;">
	<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
		<a href="{% url 'EBazaar:index' %}" class="stext-109 cl8 hov-cl1 trans-04">
			Home
			<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
		</a>

		<a href="{% url 'EBazaar:category' product.category_id.pk %}" class="stext-109 cl8 hov-cl1 trans-04">
			{{ category.category_name }}
			<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
		</a>

		<span class="stext-109 cl4">
			{{ product.product_name }}
		</span>
	</div>
</div>


<!-- Product Detail -->
<section class="sec-product-detail bg0 p-t-65 p-b-60">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-lg-7 p-b-30">
				<div class="p-l-25 p-r-30 p-lr-0-lg">
					<div class="wrap-slick3 flex-sb flex-w">
						<div class="wrap-slick3-dots"></div>
						<div class="wrap-slick3-arrows flex-sb-m flex-w"></div>

						<div class="slick3 gallery-lb">
							<div class="item-slick3" data-thumb="{% static product.image %}">
								<div class="wrap-pic-w pos-relative">
									<img src="{% static product.image %}" alt="IMG-PRODUCT">

									<a class="flex-c-m size-108 how-pos1 bor0 fs-16 cl10 bg0 hov-btn3 trans-04"
										href="{% static 'images/product-detail-01.jpg' %}">
										<i class="fa fa-expand"></i>
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-6 col-lg-5 p-b-30">
				<div class="p-r-50 p-t-5 p-lr-0-lg">
					<h4 class="mtext-105 cl2 js-name-detail p-b-14">
						{{ product.product_name }}
					</h4>

					<span class="mtext-106 cl2">
						${{ product.price }}
					</span>

					{% if product.sizes %}
					<p class="stext-102 cl3 p-t-23">
						Size : {{ product.sizes }}
					</p>
					{% endif %}

					{% if product.colors %}
					<p class="stext-102 cl3 p-t-23">
						Color : {{ product.colors }}
					</p>
					{% endif %}

					<p class="stext-102 cl3 p-t-23">
						Description : {{ product.description }}
					</p>

					<!--  -->
					<div class="p-t-33">
						<div class="flex-w flex-r-m p-b-10">
							<div class="size-204 flex-w flex-m respon6-next">
								<form action="{% url 'EBazaar:add_to_cart' product.pk %}" method="post">
									{% csrf_token %}
									<div class="wrap-num-product flex-w m-r-20 m-tb-10">
										<div class="btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m">
											<i class="fs-16 zmdi zmdi-minus"></i>
										</div>

										<input class="mtext-104 cl3 txt-center num-product" type="number"
											name="quantity" value=1>

										<div class="btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m">
											<i class="fs-16 zmdi zmdi-plus"></i>
										</div>
									</div>
									<button type="submit"
										class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04 js-addcart-detail">
										Add to cart
									</button>
								</form>

								<!-- <button
									class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04 js-addcart-detail">
									<a href="{% url 'EBazaar:add_to_cart' product.pk %}">Add to cart</a>
								</button> -->
							</div>
						</div>
					</div>

					<!--  -->
					<div class="flex-w flex-m p-l-100 p-t-40 respon7">
						<div class="flex-m bor9 p-r-10 m-r-11">
							<a href="#"
								class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 js-addwish-detail tooltip100"
								data-tooltip="Add to Wishlist">
								<i class="zmdi zmdi-favorite"></i>
							</a>
						</div>

						<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100"
							data-tooltip="Facebook">
							<i class="fa fa-facebook"></i>
						</a>

						<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100"
							data-tooltip="Twitter">
							<i class="fa fa-twitter"></i>
						</a>

						<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100"
							data-tooltip="Google Plus">
							<i class="fa fa-google-plus"></i>
						</a>
					</div>
				</div>
			</div>
		</div>

		<div class="bor10 m-t-50 p-t-43 p-b-40">
			<!-- Tab01 -->
			<div class="tab01">
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
					<li class="nav-item p-b-10">
						<a class="nav-link active" data-toggle="tab" href="#description" role="tab">Description</a>
					</li>

					<li class="nav-item p-b-10">
						<a class="nav-link" data-toggle="tab" href="#information" role="tab">Additional information</a>
					</li>

					<li class="nav-item p-b-10">
						<a class="nav-link" data-toggle="tab" href="#reviews" role="tab">Reviews (1)</a>
					</li>
				</ul>

				<!-- Tab panes -->
				<div class="tab-content p-t-43">
					<!-- - -->
					<div class="tab-pane fade show active" id="description" role="tabpanel">
						<div class="how-pos2 p-lr-15-md">
							<p class="stext-102 cl6">
								{{ product.description }}
							</p>
						</div>
					</div>

					<!-- - -->
					<div class="tab-pane fade" id="information" role="tabpanel">
						<div class="row">
							<div class="col-sm-10 col-md-8 col-lg-6 m-lr-auto">
								<ul class="p-lr-28 p-lr-15-sm">
									<li class="flex-w flex-t p-b-7">
										<span class="stext-102 cl3 size-205">
											Weight
										</span>

										<span class="stext-102 cl6 size-206">
											{{ proudct.weight }}
										</span>
									</li>

									<li class="flex-w flex-t p-b-7">
										{% if product.colors %}
										<span class="stext-102 cl3 size-205">
											Color
										</span>

										<span class="stext-102 cl6 size-206">
											{{ product.colors }}
										</span>
										{% endif %}
									</li>

									<li class="flex-w flex-t p-b-7">
										{% if product.sizes %}
										<span class="stext-102 cl3 size-205">
											Size
										</span>

										<span class="stext-102 cl6 size-206">
											{{ product.sizes }}
										</span>
										{% endif %}
									</li>
								</ul>
							</div>
						</div>
					</div>

					<!-- - -->
					<div class="tab-pane fade" id="reviews" role="tabpanel">
						<div class="row">
							<div class="col-sm-10 col-md-8 col-lg-6 m-lr-auto">
								<div class="p-b-30 m-lr-15-sm">
									<!-- Review -->
									<div class="flex-w flex-t p-b-68">
										<div class="wrap-pic-s size-109 bor0 of-hidden m-r-18 m-t-6">
											<img src="{% static 'images/avatar-01.jpg' %}" alt="AVATAR">
										</div>

										<div class="size-207">
											<div class="flex-w flex-sb-m p-b-17">
												<span class="mtext-107 cl2 p-r-20">
													Ariana Grande
												</span>

												<span class="fs-18 cl11">
													<i class="zmdi zmdi-star"></i>
													<i class="zmdi zmdi-star"></i>
													<i class="zmdi zmdi-star"></i>
													<i class="zmdi zmdi-star"></i>
													<i class="zmdi zmdi-star-half"></i>
												</span>
											</div>

											<p class="stext-102 cl6">
												Quod autem in homine praestantissimum atque optimum est, id deseruit.
												Apud ceteros autem philosophos
											</p>
										</div>
									</div>

									<!-- Add review -->
									<form class="w-full">
										<h5 class="mtext-108 cl2 p-b-7">
											Add a review
										</h5>

										<p class="stext-102 cl6">
											Your email address will not be published. Required fields are marked *
										</p>

										<div class="flex-w flex-m p-t-50 p-b-23">
											<span class="stext-102 cl3 m-r-16">
												Your Rating
											</span>

											<span class="wrap-rating fs-18 cl11 pointer">
												<i class="item-rating pointer zmdi zmdi-star-outline"></i>
												<i class="item-rating pointer zmdi zmdi-star-outline"></i>
												<i class="item-rating pointer zmdi zmdi-star-outline"></i>
												<i class="item-rating pointer zmdi zmdi-star-outline"></i>
												<i class="item-rating pointer zmdi zmdi-star-outline"></i>
												<input class="dis-none" type="number" name="rating">
											</span>
										</div>

										<div class="row p-b-25">
											<div class="col-12 p-b-5">
												<label class="stext-102 cl3" for="review">Your review</label>
												<textarea class="size-110 bor8 stext-102 cl2 p-lr-20 p-tb-10"
													id="review" name="review"></textarea>
											</div>

											<div class="col-sm-6 p-b-5">
												<label class="stext-102 cl3" for="name">Name</label>
												<input class="size-111 bor8 stext-102 cl2 p-lr-20" id="name" type="text"
													name="name">
											</div>

											<div class="col-sm-6 p-b-5">
												<label class="stext-102 cl3" for="email">Email</label>
												<input class="size-111 bor8 stext-102 cl2 p-lr-20" id="email"
													type="text" name="email">
											</div>
										</div>

										<button
											class="flex-c-m stext-101 cl0 size-112 bg7 bor11 hov-btn3 p-lr-15 trans-04 m-b-10">
											Submit
										</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="bg6 flex-c-m flex-w size-302 m-t-73 p-tb-15">
		<span class="stext-107 cl6 p-lr-25">
			SKU: {{ product.pk }}
		</span>

		<span class="stext-107 cl6 p-lr-25">
			{{ category.category_name }}
		</span>
	</div>
</section>


<!-- Related Products -->
<section class="sec-relate-product bg0 p-t-45 p-b-105">
	<div class="container">
		<div class="p-b-45">
			<h3 class="ltext-106 cl5 txt-center">
				Related Products
			</h3>
		</div>

		<!-- Slide2 -->
		<div class="wrap-slick2">
			{% for products in all_products %}
			<div class="slick2">
				{% for related_products in products %}
				<div class="item-slick2 p-l-15 p-r-15 p-t-15 p-b-15">
					<!-- Block2 -->
					<div class="block2">
						<div class="block2-txt flex-w flex-t p-t-14">
							<div class="block2-pic hov-img0">
								<img src="{% static related_products.image %}" alt="IMG-PRODUCT">
							</div>
							<div class="block2-txt-child1 flex-col-l ">
								<a href="{% url 'EBazaar:product_details' category_id=related_products.category_id.pk product_id=related_products.pk %}"
									class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
									{{ related_products.product_name }}
								</a>

								<span class="stext-105 cl3">
									${{ related_products.price }}
								</span>
							</div>

							<div class="block2-txt-child2 flex-r p-t-3">
								<a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
									<img class="icon-heart1 dis-block trans-04"
										src="{% static 'images/icons/icon-heart-01.png' %}" alt="ICON">
									<img class="icon-heart2 dis-block trans-04 ab-t-l"
										src="{% static 'images/icons/icon-heart-02.png' %}" alt="ICON">
								</a>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
			{% endfor %}
		</div>
	</div>
</section>
{% endblock %}